endpoints:
  receiveorder_uploadpattern:
    info: '受注一括登録パターン - 情報取得'
  receiveorder_base:
    count: '受注伝票 - 件数取得'
    search: '受注伝票 - 検索'
    update: '受注伝票 - 更新'
    upload: '受注伝票 - アップロード'
    receipted: '受注伝票 - 納品書印刷済み'
    shipped: '受注伝票 - 出荷確定処理'
    labelprinted: '受注伝票 - 配送情報出力済み'
    divide: '受注伝票 - 分割'
  receiveorder_row:
    count: '受注明細 - 件数取得'
    search: '受注明細 - 検索'
  receiveorder_forwardingagent:
    count: '発送方法別区分 - 件数取得'
    search: '発送方法別区分 - 検索'
  receiveorder_confirm:
    count: '受注確認内容 - 件数取得'
    search: '受注確認内容 - 検索'
  master_goods:
    count: '商品マスタ - 件数取得'
    search: '商品マスタ - 検索'
    upload: '商品マスタ - アップロード'
  master_goodstag:
    count: '商品タグ - 件数取得'
    search: '商品タグ - 検索'
  master_mailtag:
    count: 'メールタグ - 件数取得'
    search: 'メールタグ - 検索'
  master_stock:
    count: '在庫マスタ - 件数取得'
    search: '在庫マスタ - 検索'
  master_supplier:
    count: '仕入先マスタ - 件数取得'
    search: '仕入先マスタ - 検索'
  master_wholesale:
    count: '卸先マスタ - 件数取得'
    search: '卸先マスタ - 検索'
  master_stockiohistory:
    count: '在庫入出庫履歴 - 件数取得'
    search: '在庫入出庫履歴 - 検索'
  master_pagebase:
    count: '商品ページ（基本） - 件数取得'
    search: '商品ページ（基本） - 検索'
  master_pagebasevariationoroption:
    count: '商品ページ（基本-項目選択肢又はオプション） - 件数取得'
    search: '商品ページ（基本-項目選択肢又はオプション） - 検索'
  master_shop:
    count: '店舗マスタ - 件数取得'
    search: '店舗マスタ - 検索'
    checkconnect: '店舗マスタ - 店舗接続確認'
  master_goodsimage:
    count: '商品画像 - 件数取得'
    search: '商品画像 - 検索'
  master_goodsimagetag:
    count: '商品画像分類タグ - 件数取得'
    search: '商品画像分類タグ - 検索'
  master_goodscategory:
    count: '商品カテゴリ - 件数取得'
    search: '商品カテゴリ - 検索'
  login_user:
    info: 'ログインユーザー - 情報取得'
  login_company:
    info: 'ログイン企業 - 情報取得'
  system_credittype:
    info: 'クレジット種類区分 - 情報取得'
  system_creditauthorizationcenter:
    info: 'クレジットオーソリセンター区分 - 情報取得'
  system_creditapprovaltype:
    info: 'クレジット承認区分 - 情報取得'
  system_order:
    info: '発注区分 - 情報取得'
  system_ordercondition:
    info: '発注条件区分 - 情報取得'
  system_delivery:
    info: '発送方法区分 - 情報取得'
  system_fraction:
    info: '端数処理区分 - 情報取得'
  system_returnedreason:
    info: '返品事由区分 - 情報取得'
  system_canceltype:
    info: '受注キャンセル区分 - 情報取得'
  system_orderstatus:
    info: '受注状態区分 - 情報取得'
  system_importantcheck:
    info: '重要チェック区分 - 情報取得'
  system_confirmcheck:
    info: '確認チェック区分 - 情報取得'
  system_customertype:
    info: '顧客区分 - 情報取得'
  system_deposittype:
    info: '入金区分 - 情報取得'
  system_iotype:
    info: '入出荷区分 - 情報取得'
  system_select:
    info: '商品選択肢区分 - 情報取得'
  system_paymentmethod:
    info: '支払区分 - 情報取得'
  system_payout:
    info: '支払方法区分 - 情報取得'
  system_socialinsurance:
    info: '社会保険区分 - 情報取得'
  system_goodstype:
    info: '商品区分 - 情報取得'
  system_goodsstatus:
    info: '商品ステータス区分 - 情報取得'
  system_merchandise:
    info: '取扱区分 - 情報取得'
  system_importtype:
    info: '取込種類区分 - 情報取得'
  system_forwardingmethod:
    info: '輸送区分 - 情報取得'
  system_tax:
    info: '税区分 - 情報取得'
  system_itemname:
    info: '項目名 - 情報取得'
  system_pagestatus:
    info: 'ページステータス区分 - 情報取得'
  system_que:
    count: 'アップロードキュー - 件数取得'
    search: 'アップロードキュー - 検索'
  system_authorizationtype:
    info: 'オーソリ区分 - 情報取得'
  system_currencyunit:
    info: '通貨単位区分 - 情報取得'
  system_mall:
    count: 'モール - 件数取得'
    search: 'モール - 検索'
  system_imagetag:
    count: '画像分類タグ - 件数取得'
    search: '画像分類タグ - 検索'
  system_mallcategory:
    count: 'モールカテゴリ - 件数取得'
    search: 'モールカテゴリ - 検索'
